name: PR check workflow

on:
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Echo hello world
        run: |
          echo "Hello world"
      - uses: actions/checkout@v2
      - name: build the docker image
        env:
          TAG: ${{github.sha}}
        run: |
          docker build -t yashodperera/go-demo:$TAG .
      - name: Complete Flow
        run: |
          echo "completed"

        
